# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://blog-posting.github.io"

# Google Analytics
google_analytics: UA-152555960-2

# Author
author:
  name:         Blog-posting
  url:          https://blog-posting.github.io
  email:        ksy90101@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale